
exports.seed = function(knex, Promise) {
  return knex('values').insert([
   {"value_name": "Authenticity"},
   {"value_name": "Achievement"},
   {"value_name": "Adventure"},
   {"value_name": "Authority"},
   {"value_name": "Autonomy"},
   {"value_name": "Balance"},
   {"value_name": "Beauty"},
   {"value_name": "Boldness"},
   {"value_name": "Compassion"},
   {"value_name": "Challenge"},
   {"value_name": "Citizenship"},
   {"value_name": "Community"},
   {"value_name": "Competency"},
   {"value_name": "Contribution"},
   {"value_name": "Creativity"},
   {"value_name": "Curiosity"},
   {"value_name": "Determination"},
   {"value_name": "Fairness"},
   {"value_name": "Faith"},
   {"value_name": "Fame"},
   {"value_name": "Friendships"},
   {"value_name": "Fun"},
   {"value_name": "Growth"},
   {"value_name": "Happiness"},
   {"value_name": "Honesty"},
   {"value_name": "Humor"},
   {"value_name": "Influence"},
   {"value_name": "Inner Harmony"},
   {"value_name": "Justice"},
   {"value_name": "Kindness"},
   {"value_name": "Knowledge"},
   {"value_name": "Leadership"},
   {"value_name": "Learning"},
   {"value_name": "Love"},
   {"value_name": "Loyalty"},
   {"value_name": "Meaningful Work"},
   {"value_name": "Openness"},  
   {"value_name": "Optimism"},
   {"value_name": "Peace"},
   {"value_name": "Pleasure"},
   {"value_name": "Poise"},
   {"value_name": "Popularity"},
   {"value_name": "Recognition"},
   {"value_name": "Religion"},
   {"value_name": "Reputation"},
   {"value_name": "Respect"},
   {"value_name": "Responsibility"},
   {"value_name": "Security"},
   {"value_name": "Self-Respect"},
   {"value_name": "Service"},
   {"value_name": "Spirituality"},
   {"value_name": "Stability"},
   {"value_name": "Success"},
   {"value_name": "Status"},
   {"value_name": "Trustworthiness"},
   {"value_name": "Wealth"},
   {"value_name": "Wisdom"},
   {"value_name": "Family"},
   {"value_name": "Career"},
   {"value_name": "Health"}
  ]);
};

